import streamlit as st
# from streamlit_extras.switch_page_button import switch_page

st.set_page_config(
    page_title="Hyper CH4",
    page_icon="🛰️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# decrease pad to page top
st.write('<style>div.block-container{padding-top:2rem;}</style>', unsafe_allow_html=True)

# set title
st.title('👋 :orange[Hello, Hyper User!]')

st.markdown('### Introduction')
st.markdown('In 20 years, methane (CH$_4$) exhibits a global warming potential 84 times greater than that of carbon dioxide. \
            The waste management sector contributes to 21.5% of total anthropogenic methane emissions, with 44% of these emissions originating from landfills. \
            Landfills are responsible for approximately 55% of the global uncertainty share. \
            We use this tool to check CH$_4$ plumes from landfills. Ofc, please feel free to use it for your own research.')
st.markdown('This website displays the **CH$_4$** enhancement (ppb) L2B products \
                retrieved from **EnMAP, EMIT, and PRISMA L1B data**. \
             The products are generated by the [HyperCH4](https://github.com/zxdawn/HyperCH4) package. \
             These data are processed to NetCDF products with UTM projection, \
                making them more accessible for viewing and analysis.')

st.markdown('### Steps (Data Preparation)')

st.markdown('- Run the `l2_plot.py` script to plot the L2B data and export them as HTML files.')
st.markdown('- Open one interested HTML file under the L2B output folder.')
st.markdown('- Add markers to plume sources using the *Marker* tool on the left.')
st.markdown('- Generate geojson files by clicking the *Export* button.')
st.markdown('- If exported geojson file is not under the L2B directory, please move it manually.')
st.markdown('- Explore the interactive images by typing the L2B *folder path* in the **🛰 Quickview page**.')

# want_to_contribute = st.button("🛰 Quickview page")
# if want_to_contribute:
#     switch_page("Overview")
